### ISSUE TITLE
TAB screen stays open

### ISSUE THREAD

**Issue by BielefeldJ** [Rylius/VU-Racing#3]
Sometimes when you press TAB, the blue scoreboard screen stays open. It disappears when the game loads a new map.
Screenshot:
![image](https://user-images.githubusercontent.com/10292673/102817385-fbfec080-43cf-11eb-88c5-2bef260e86b2.png)

Installed plugins:
gameAdmin

**Comment by Rylius** [comment]
Can you check the server logs for stacktraces? I'm getting some client errors related to scoreboard updates which may be related to this issue.

**Comment by BielefeldJ** [comment]
The server didnt create a logfile and I dont see any errors in the GUI.
Do I need to enable logging somewhere? 

Edit: The Server crashed ^^

**Comment by Rylius** [comment]
Oops

Kinda depends how you're running the server, but it's possible there just aren't any logs :(

**Comment by BielefeldJ** [comment]
Well... I just started "VU Server" from the start menu :P

**Comment by Rylius** [comment]
That should open a window which contains the server log. If nothing in there looks like an error that's fine too :)

**Comment by BielefeldJ** [comment]
Yea. Thats what i meant with " I don't see any errors in the GUI." ^^

**Comment by Rylius** [comment]
Should be fixed by 53226b18d3677f100aed4c66c1c4ad70a254c560, 454cf5320dcc0d92bc33afbebc1bcc658679e2ec, c1e1db3828fe018dedcd15433e3837a3b53be207 and 766de6438c9a1bbda262074e2703aec7e7d1ff59

(I'll release a proper update soon)

**Comment by BielefeldJ** [comment]
Jup, It is fixed! Thanks :)
