### ISSUE TITLE
Seatswitching sometimes allowed.

### ISSUE THREAD

**Issue by BielefeldJ** [Rylius/VU-Racing#4]
Sometimes a player can switch to the backseat and can use weapons.
But this was not that big of a deal. Just wanna mention it.

Installed plugins:
gameAdmin

PS: Nice mod! We played with about 30 player. Its really fun!

**Comment by Rylius** [comment]
That... really shouldn't be possible. :)
I'll look into it!

Glad you enjoyed it!

**Comment by BielefeldJ** [comment]
After i finished the first round, i was able to switch.
Here is a screen: 

![image](https://user-images.githubusercontent.com/10292673/102818047-2ac96680-43d1-11eb-8f3b-c0c156698ace.png)

**Comment by Rylius** [comment]
This might be caused by people spawning on squad members (but I'm not entirely sure).

Set `vu.SquadSize` to `1` as a workaround.

**Comment by Rylius** [comment]
In any case, f8d34e13f8fafcdc4a3e976132b9c2c92174b0f3 disables the passenger seat entirely. :)
